import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogBody, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { REQUEST_BOARD_KINDS, type RequestBoard, type RequestBoardKind } from "@/data/schema"

export interface RequestBoardValues { name: string; kind: RequestBoardKind; team: string; note: string; createdBy: string; createdByName: string }
export function RequestBoardDialog({ open, mode, board, boards, teams, isOwner, canDelete, onSubmit, onDelete, onOpenChange }: { open: boolean; mode: "create" | "edit"; board?: RequestBoard; boards: readonly RequestBoard[]; teams: string[]; isOwner: boolean; canDelete: boolean; onSubmit: (values: RequestBoardValues) => void; onDelete: () => void; onOpenChange: (open: boolean) => void }) {
  const [value, setValue] = useState<RequestBoardValues>({ name: "", kind: "시즌 개발", team: "", note: "", createdBy: "", createdByName: "" })
  useEffect(() => { setValue(board ? { name: board.name, kind: board.kind, team: board.team, note: board.note, createdBy: board.createdBy, createdByName: board.createdByName } : { name: "", kind: "시즌 개발", team: "", note: "", createdBy: "", createdByName: "" }) }, [board, open])
  const name = value.name.trim(); const duplicate = boards.some((item) => item.status === "진행" && item.boardId !== board?.boardId && item.name.trim() === name)
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{mode === "create" ? "새 보드" : "보드 정보"}</DialogTitle></DialogHeader><DialogBody className="grid gap-3"><label className="grid gap-1 text-xs">이름<Input value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></label>{duplicate ? <p className="text-xs text-[var(--destructive)]">진행 중인 보드와 같은 이름은 쓸 수 없습니다.</p> : null}<label className="grid gap-1 text-xs">종류<Select value={value.kind} onValueChange={(kind) => setValue({ ...value, kind: kind as RequestBoardKind })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{REQUEST_BOARD_KINDS.map((kind) => <SelectItem key={kind} value={kind}>{kind}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-1 text-xs">소팀<Input list="request-board-teams" value={value.team} onChange={(event) => setValue({ ...value, team: event.target.value })} /></label><datalist id="request-board-teams">{teams.map((team) => <option key={team} value={team} />)}</datalist><label className="grid gap-1 text-xs">메모<textarea className="min-h-20 rounded border border-[var(--border)] bg-[var(--card)] p-2" value={value.note} onChange={(event) => setValue({ ...value, note: event.target.value })} /></label>{mode === "edit" && isOwner ? <div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-xs">담당 이메일<Input value={value.createdBy} onChange={(event) => setValue({ ...value, createdBy: event.target.value })} /></label><label className="grid gap-1 text-xs">담당 이름<Input value={value.createdByName} onChange={(event) => setValue({ ...value, createdByName: event.target.value })} /></label></div> : null}</DialogBody><DialogFooter className="justify-between">{mode === "edit" && canDelete ? <Button type="button" variant="destructive" onClick={() => { if (window.confirm("빈 보드를 삭제할까요?")) onDelete() }}>보드 삭제</Button> : <span />}<div className="flex gap-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>취소</Button><Button type="button" disabled={!name || duplicate} onClick={() => onSubmit({ ...value, name, team: value.team.trim(), note: value.note.trim() })}>저장</Button></div></DialogFooter></DialogContent></Dialog>
}

export function MoveStyleDialog({ open, boards, onMove, onOpenChange }: { open: boolean; boards: readonly RequestBoard[]; onMove: (boardId: string) => void; onOpenChange: (open: boolean) => void }) {
  const [boardId, setBoardId] = useState(boards[0]?.boardId ?? "")
  useEffect(() => { setBoardId(boards[0]?.boardId ?? "") }, [boards, open])
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>다른 보드로 옮기기</DialogTitle></DialogHeader><DialogBody><Select value={boardId} onValueChange={setBoardId}><SelectTrigger><SelectValue placeholder="보드 선택" /></SelectTrigger><SelectContent>{boards.map((board) => <SelectItem key={board.boardId} value={board.boardId}>{board.name}</SelectItem>)}</SelectContent></Select></DialogBody><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>취소</Button><Button disabled={!boardId} onClick={() => onMove(boardId)}>옮기기</Button></DialogFooter></DialogContent></Dialog>
}
